# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua

exec-once = waybar
exec-once = swaybg -i /home/naufal/Downloads/wallhaven-g86mme_1366x768.png -m fill

# ENABLE CHROME CASTING

# exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP


$mainMod = SUPER
$terminal = kitty
$fileManager = kitty yazi
$menu = rofi -show drun
$firefox = firefox

bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu
bind = $mainMod, B, exec, $firefox

# Directional focus with SUPER + Arrow Keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Classic Alt-Tab (cycles through open windows)
bind = ALT, Tab, cyclenext,
bind = ALT, Tab, bringactivetotop,


# Toggle Fullscreen with SUPER + F
bind = $mainMod, F, fullscreen, 1

# Move windows around (and across monitors) with SUPER + SHIFT + Arrow Keys
bind = $mainMod SHIFT, left, movewindow, l
bind = $mainMod SHIFT, right, movewindow, r
bind = $mainMod SHIFT, up, movewindow, u
bind = $mainMod SHIFT, down, movewindow, d

# Screenshot a window
bind = $mainMod, PRINT, exec, hyprshot -m window
# Screenshot a monitor
bind = , PRINT, exec, hyprshot -m output
# Screenshot a region
bind = $mainMod SHIFT, PRINT, exec, hyprshot -m region



# Screen Brightness
bindel = ,XF86MonBrightnessUp, exec, brightnessctl s 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl s 5%-

# Firefox PiP
windowrule = match:title ^(Picture-in-Picture)$, float on
windowrule = match:title ^(Picture-in-Picture)$, pin on

# Move floating windows with SUPER + left mouse button drag
bindm = SUPER, mouse:272, movewindow

# Resize floating windows with SUPER + right mouse button drag
bindm = SUPER, mouse:273, resizewindow



# ~/.config/hypr/hyprland.conf
general {
    col.active_border   = rgb(ff6600)   # NERV orange
    col.inactive_border = rgb(1a3a1a)   # dark green
    border_size         = 2
    gaps_in             = 4
    gaps_out            = 6
}

decoration {
    rounding = 0

    shadow {
        enabled = false
    }

    blur {
        enabled = false
    }
}

animations { enabled = false }
